decorators:
  scalar: "double"
  scalar_function: "double"
  scalar_cast: "double"
  scalar_parameter: "const double&"
  n_thermo_order: "7"
  scalar_list: "std::array"
  temperature_monomial_typedef: "std::array<double, n_order_thermo>"
  temperature_monomial_function: "TemperatureMonomial"
  temperature_monomial: "TemperatureMonomial"
  temperature_monomial_parameter: "const TemperatureMonomial&"

  temperature_energy_monomial_function: "TemperatureEnergyMonomial"
  temperature_energy_monomial: "TemperatureEnergyMonomial"
  temperature_energy_monomial_parameter: "const TemperatureEnergyMonomial&"

  temperature_gibbs_monomial_function: "TemperatureGibbsMonomial"
  temperature_gibbs_monomial: "TemperatureGibbsMonomial"
  temperature_gibbs_monomial_parameter: "const TemperatureGibbsMonomial&"

  index: "int"
  string: "std::string"

  species_typedef: "std::array<double, n_species>"
  species: "Species"
  species_function: "Species"
  species_cast: "Species"
  species_parameter: "const Species&"
  species_element: "species[{i}]"
  
  arbitrary_element: "{name}[{{i}}]"

  reactions_typedef: "std::array<double, n_reactions>"
  reactions: "Reactions"
  reactions_function: "Reactions"
  reactions_cast: "Reactions"
  reactions_parameter: "const Reactions&"
  reactions_element: "reactions[{i}]"

  source_element: "net_production_rates[{i}]"
  const_option: ""
  constexpr: "constexpr"
  device_option: ""
  expmath: "std::exp"
  powmath: "std::pow"
  logmath: "std::log"
  log10math: "std::log10"

  device_sum: "std::accumulate(a_s.begin(), a_s.end(), {scalar_cast}(0.0))"
  device_fill: "std::fill(b_s.begin(), b_s.end(), a)"
  device_transform: "std::transform(b_s.begin(), b_s.end(), c_s.begin(), [&a]({scalar} s) {{ return a * s; }});"
  device_element_sum: "std::transform(a_s.begin(), a_s.end(), b_s.begin(), c_s.begin(), []({scalar_parameter} a, {scalar_parameter} b) {{ return a + b; }});"
  device_element_multiply: "std::transform(a_s.begin(), a_s.end(), b_s.begin(), c_s.begin(), []({scalar_parameter} a, {scalar_parameter} b) {{ return a * b; }});"
  sum: "sum_gen"
  fill: "fill_gen"
  scale: "scale_gen"

build:
  chemgen_smp: None 
  chemgen_optimized: O2

