decorators:
  scalar: "double"
  scalar_function: "double"
  scalar_cast: "double"
  scalar_parameter: "const double&"
  species_typedef: "std::array<double, n_species>"
  species: "Species"
  species_function: "Species"
  species_cast: "Species"
  species_parameter: "const Species&"
  species_element: "species[{i}]"
  source_element: "net_production_rates[{i}]"
  const_option: ""
  constexpr: "constexpr"
  device_option: ""
  expmath: "std::exp"
  powmath: "std::pow"
  logmath: "std::log"

decorators_float:
  scalar: "float"
  scalar_function: "float"
  scalar_cast: "float"
  scalar_parameter: "const float&"
  const_option: ""
  constexpr: "constexpr"
  device_option: ""
  expmath: "std::exp"
  powmath: "std::pow"
  logmath: "std::log"

