test_conditions:
  temperature: 1800
  pressure: 101325.0
  species:
    - name: O2
      MoleFraction: 0.2
    - name: N2
      MoleFraction: 0.4
    - name: H2
      MoleFraction: 0.2  
    - name: C2H4
      MoleFraction: 0.2  
