#include <cmath>
#include <algorithm>
#include <array>
#include <chrono>
#include <iostream>

#define CHEMGEN_EIGEN
#define CHEMGEN_EIGEN_SPARSE
#ifdef CHEMGEN_EIGEN
#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <unsupported/Eigen/IterativeSolvers>
#endif
        #include "types_inl.h"
#include "generated_constants.h"
#include "multiply_divide.h"
#include "pow_gen.h"
#include "exp_gen.h"
#include "array_handling.h"
#include "constants.h"
#include "thermally_perfect.h"
#include "arrhenius.h"
#include "third_body.h"
#include "falloff_troe.h"
#include "falloff_lindemann.h"
#include "falloff_sri.h"
#include "pressure_dependent_arrhenius.h"
#include "direct.h"
#include "reactions.h"
#include "source.h"
#include "chemical_state_functions.h"
